export const CATALOG: Record<string, string[]> = {
  Outdoors: [
    "Hiking",
    "Camping",
    "Bouldering",
    "Rock Climbing",
    "Trail Running",
    "Cycling",
    "Birdwatching",
    "Skiing",
    "Snowboarding",
  ],
  Sports: [
    "Football",
    "Basketball",
    "Tennis",
    "Table Tennis",
    "Badminton",
    "Swimming",
    "Martial Arts",
  ],
  Creative: [
    "Painting",
    "Photography",
    "Writing",
    "Calligraphy",
    "UI/UX",
    "Graphic Design",
    "Music Production",
  ],
  Tech: [
    "Web Development",
    "Data Science",
    "Machine Learning",
    "Cybersecurity",
    "Open Source",
    "Blockchain",
    "DevOps",
  ],
  Entertainment: [
    "Sci-Fi",
    "Fantasy",
    "Anime",
    "Board Games",
    "Video Games",
    "Podcasts",
    "Movies",
    "TV Shows",
  ],
  Wellness: [
    "Meditation",
    "Yoga",
    "Mindfulness",
    "Running",
    "Strength Training",
    "Nutrition",
  ],
  "Food & Drink": [
    "Baking",
    "Coffee",
    "Tea",
    "Vegan Cooking",
    "BBQ",
    "Wine Tasting",
    "Cocktails",
  ],
};